import os
OPENSHIFT_TOKEN = os.environ.get("OS_OPENSHIFT_TOKEN")
FLASK_APP_URL = 'http://' + str(os.environ.get("HOST","localhost")) +':'+str(os.environ.get("PORT", 8000))
METERING_ROUTE_LIST_ALL_PROJECTS = os.environ.get("OS_LIST_ALL_PROJECTS_URL")
METERING_ROUTE_NAMESPACE_CPU_REQUEST_HOURLY = os.environ.get("OS_NAMESPACE_CPU_REQUEST_HOURLY")
METERING_ROUTE_NAMESPACE_CPU_REQUEST_DAILY = os.environ.get("OS_NAMESPACE_CPU_REQUEST_DAILY")
METERING_ROUTE_NAMESPACE_CPU_REQUEST_WEEKLY= os.environ.get("OS_NAMESPACE_CPU_REQUEST_WEEKLY")
METERING_ROUTE_NAMESPACE_CPU_REQUEST_MONTHLY = os.environ.get("OS_NAMESPACE_CPU_REQUEST_MONTHLY")
